# This file is managed by `repo_helper`. Don't edit it directly
---

language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
  - 'pypy3'

install:

  - pip install pip  --upgrade
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi
  - deploy_conda


jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/flake8-sphinx-links
        provider: pypi
        user: "DomDF"
        password:
          secure: P72e1+0LhtTw7dVGOAkvyfauWb2ywwLjdix+0y1eaI+f2i+CBAVtZ7iBLskFCSU7HN6ogkUFBGjrKvZTmvhE133W1ew4NJlqeHAlg6b2Sw40rmyXV7mAEf7rRJyWnqD3JFPbZ/vWC2zOsRA0xUpfl5V6rR50R4EeCZkg2QtBlIcj3HMSH0zo2ROx7tLD6HLBReBhlj2707xfv+Hvs7q4j7qSaMjKTTlc23dr3cq2LMgifE4+sIRD3W9Qsza6CNM6kGAEBuKgNHBhDpi2A24DWy+3UqRXWgBWNTav9rAHACRBTuGlc3zsnN/f6KigNpPUVk89SUN4fqtZXC8nPuYOSof8h3o1S1bKlif2cYNlW856eQP3F0Aq754SLQWaYr0GerYgeacHLmbQC6MVICW/y7bfVPtDjIjqE13xq9TSMeFvEdGRuC43B6GswTVhyLm7yLTXJaHrgqqLMRduSY34Welf+ej7C0eWlWQrG8YyHwNY931pPJxErQqxkSTO3CVnPmomvlzbAjAOsJQmzvAs6DJVaSYbMRj//+7DSfI9tepB2EqLcIQ6wPeTTW31SlX6Tc+7ez9lNNgdk5yxK7Ovmpot8/oGKJ1cMeAl22Gnrkmb8oAHXxCNvtjgaJjxHElSd5HknY9tveaQNZfw88EX3/66YHMNEkLWUJ1RKkZCcoQ=
        distributions: "sdist bdist_wheel"
        skip_existing: true
    - stage: deploy_conda
      python: "3.6"
      addons:
        apt:
          update: true
      install:
        - pip install rst2txt yolk3k
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - chmod +x .ci/travis_deploy_conda.sh
      script: skip
      deploy:
        on:
          repo: domdfcoding/flake8-sphinx-links
        provider: script
        script: .ci/travis_deploy_conda.sh || return 1;
